import { useState } from 'react'
import { ClipboardList, Loader2, Bot, AlertTriangle, CheckCircle, TrendingUp } from 'lucide-react'
import { api } from '../api/client'
import type { Stats, Exception } from '../types'

interface Props {
  stats: Stats | null
  exceptions: Exception[]
}

export function ShiftSummary({ stats, exceptions }: Props) {
  const [summary, setSummary] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [generatedAt, setGeneratedAt] = useState<string | null>(null)

  const generate = async () => {
    setLoading(true)
    try {
      const result = await api.agent.shiftSummary()
      setSummary(result.summary)
      setGeneratedAt(result.generated_at)
    } catch (err) {
      setSummary('Error generating summary. Make sure the backend is running.')
    } finally {
      setLoading(false)
    }
  }

  const openExceptions = exceptions.filter(e => e.status === 'open')
  const resolvedExceptions = exceptions.filter(e => e.status === 'resolved')

  return (
    <div className="max-w-3xl mx-auto">
      <div className="flex items-center gap-3 mb-6">
        <ClipboardList size={20} className="text-blue-600" />
        <div>
          <h1 className="text-xl font-bold text-slate-900">Shift Summary</h1>
          <p className="text-sm text-slate-500">End-of-shift briefing generated by the agent</p>
        </div>
        <button
          onClick={generate}
          disabled={loading}
          className="ml-auto flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 disabled:opacity-60 text-white text-sm font-medium rounded-lg transition-colors"
        >
          {loading ? <Loader2 size={15} className="animate-spin" /> : <Bot size={15} />}
          {loading ? 'Generating…' : 'Generate Summary'}
        </button>
      </div>

      {/* Quick stats grid */}
      {stats && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">
          <StatCard
            label="Total Orders"
            value={stats.total_orders}
            icon={<ClipboardList size={18} />}
            color="blue"
          />
          <StatCard
            label="Delivered"
            value={stats.status_breakdown['delivered'] ?? 0}
            icon={<CheckCircle size={18} />}
            color="green"
          />
          <StatCard
            label="Open Exceptions"
            value={stats.open_exceptions}
            icon={<AlertTriangle size={18} />}
            color={stats.open_exceptions > 0 ? 'red' : 'slate'}
          />
          <StatCard
            label="CS Pending"
            value={stats.pending_notifications}
            icon={<TrendingUp size={18} />}
            color={stats.pending_notifications > 0 ? 'amber' : 'slate'}
          />
        </div>
      )}

      {/* Window breakdown */}
      {stats && (
        <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6">
          <h2 className="text-sm font-semibold text-slate-700 mb-3">Delivery Windows</h2>
          <div className="space-y-2">
            {Object.entries(stats.window_stats).sort().map(([window, ws]) => {
              const pct = ws.total > 0 ? Math.round(((ws.delivered + ws.dispatched) / ws.total) * 100) : 0
              return (
                <div key={window} className="flex items-center gap-3">
                  <span className="text-sm font-mono text-slate-600 w-24 flex-shrink-0">{window}</span>
                  <div className="flex-1 bg-slate-100 rounded-full h-2">
                    <div
                      className={`h-2 rounded-full transition-all ${
                        ws.at_risk > 0 ? 'bg-amber-400' : 'bg-green-400'
                      }`}
                      style={{ width: `${pct}%` }}
                    />
                  </div>
                  <div className="text-xs text-slate-500 w-32 flex-shrink-0">
                    {ws.delivered + ws.dispatched}/{ws.total} done
                    {ws.at_risk > 0 && (
                      <span className="text-red-600 ml-1">· {ws.at_risk} at risk</span>
                    )}
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      )}

      {/* Exception summary */}
      {exceptions.length > 0 && (
        <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6">
          <h2 className="text-sm font-semibold text-slate-700 mb-3">
            Exceptions — {openExceptions.length} open, {resolvedExceptions.length} resolved
          </h2>
          <div className="space-y-1.5">
            {exceptions.slice(0, 8).map(e => (
              <div key={e.id} className="flex items-center gap-2 text-xs">
                <div className={`w-1.5 h-1.5 rounded-full flex-shrink-0 ${
                  e.severity === 'high' ? 'bg-red-500' :
                  e.severity === 'medium' ? 'bg-amber-400' : 'bg-slate-400'
                }`} />
                <span className="font-medium capitalize text-slate-600">{e.type.replace(/_/g, ' ')}</span>
                <span className="text-slate-400 flex-1 truncate">{e.description}</span>
                <span className={`px-1.5 py-0.5 rounded text-xs font-medium ${
                  e.status === 'resolved' ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'
                }`}>
                  {e.status}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* AI generated narrative */}
      {loading && (
        <div className="bg-white rounded-xl border border-slate-200 p-8 flex flex-col items-center gap-3 text-slate-500">
          <Loader2 size={28} className="animate-spin text-blue-500" />
          <p className="text-sm">Agent is writing your shift briefing…</p>
        </div>
      )}

      {summary && !loading && (
        <div className="bg-white rounded-xl border border-slate-200 p-5">
          <div className="flex items-center gap-2 mb-4">
            <Bot size={15} className="text-blue-500" />
            <span className="text-sm font-semibold text-slate-700">Agent Shift Briefing</span>
            {generatedAt && (
              <span className="text-xs text-slate-400 ml-auto">
                {new Date(generatedAt).toLocaleTimeString()}
              </span>
            )}
          </div>
          <div className="prose prose-sm max-w-none text-slate-700 whitespace-pre-wrap leading-relaxed text-sm">
            {summary}
          </div>
        </div>
      )}
    </div>
  )
}

function StatCard({
  label,
  value,
  icon,
  color,
}: {
  label: string
  value: number
  icon: React.ReactNode
  color: string
}) {
  const colorMap: Record<string, string> = {
    blue: 'bg-blue-50 text-blue-700 border-blue-100',
    green: 'bg-green-50 text-green-700 border-green-100',
    red: 'bg-red-50 text-red-700 border-red-100',
    amber: 'bg-amber-50 text-amber-700 border-amber-100',
    slate: 'bg-slate-50 text-slate-600 border-slate-200',
  }
  return (
    <div className={`rounded-xl border p-4 ${colorMap[color] ?? colorMap.slate}`}>
      <div className="flex items-center gap-2 mb-1 opacity-75">{icon}</div>
      <div className="text-2xl font-bold">{value}</div>
      <div className="text-xs font-medium opacity-75 mt-0.5">{label}</div>
    </div>
  )
}
